// Code generated by qtc from "gen.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line gen.qtpl:1
package main

//line gen.qtpl:3
import "strings"

//line gen.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line gen.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line gen.qtpl:6
type Context struct {
	Pkg     string
	Structs []Struct
	Uuid    string
}

//line gen.qtpl:13
func streamtoLower(qw422016 *qt422016.Writer, str string) {
//line gen.qtpl:13
	qw422016.N().S(`
`)
//line gen.qtpl:15
	qw422016.N().S(strings.ToLower(str))
//line gen.qtpl:16
	qw422016.N().S(`
`)
//line gen.qtpl:17
}

//line gen.qtpl:17
func writetoLower(qq422016 qtio422016.Writer, str string) {
//line gen.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line gen.qtpl:17
	streamtoLower(qw422016, str)
//line gen.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line gen.qtpl:17
}

//line gen.qtpl:17
func toLower(str string) string {
//line gen.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line gen.qtpl:17
	writetoLower(qb422016, str)
//line gen.qtpl:17
	qs422016 := string(qb422016.B)
//line gen.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line gen.qtpl:17
	return qs422016
//line gen.qtpl:17
}

//line gen.qtpl:19
func StreamCsvTemplate(qw422016 *qt422016.Writer, ctx Context) {
//line gen.qtpl:19
	qw422016.N().S(`
package `)
//line gen.qtpl:20
	qw422016.N().S(ctx.Pkg)
//line gen.qtpl:20
	qw422016.N().S(`

import (
    "fmt"
    "strconv"
)

`)
//line gen.qtpl:27
	for _, str := range ctx.Structs {
//line gen.qtpl:27
		qw422016.N().S(`
func (s *`)
//line gen.qtpl:28
		qw422016.N().S(str.StructName)
//line gen.qtpl:28
		qw422016.N().S(`) ParseCSV(rec []string) error {
    `)
//line gen.qtpl:29
		for _, f := range str.Fields {
//line gen.qtpl:29
			qw422016.N().S(`
        `)
//line gen.qtpl:30
			if f.Omitempty {
//line gen.qtpl:30
				qw422016.N().S(`
        if rec[`)
//line gen.qtpl:31
				qw422016.N().D(f.Position)
//line gen.qtpl:31
				qw422016.N().S(`] != "" {
        `)
//line gen.qtpl:32
			}
//line gen.qtpl:32
			qw422016.N().S(`
        `)
//line gen.qtpl:33
			switch f.Type {
//line gen.qtpl:34
			case "string":
//line gen.qtpl:34
				qw422016.N().S(`
        s.`)
//line gen.qtpl:35
				qw422016.N().S(f.Name)
//line gen.qtpl:35
				qw422016.N().S(` = rec[`)
//line gen.qtpl:35
				qw422016.N().D(f.Position)
//line gen.qtpl:35
				qw422016.N().S(`]
        `)
//line gen.qtpl:36
			case "int32":
//line gen.qtpl:36
				qw422016.N().S(`
        `)
//line gen.qtpl:37
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:37
				qw422016.N().S(`, err := strconv.ParseInt(rec[`)
//line gen.qtpl:37
				qw422016.N().D(f.Position)
//line gen.qtpl:37
				qw422016.N().S(`], 0, 32)
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line gen.qtpl:39
				qw422016.N().S(f.Name)
//line gen.qtpl:39
				qw422016.N().S(` at index: %d", `)
//line gen.qtpl:39
				qw422016.N().D(f.Position)
//line gen.qtpl:39
				qw422016.N().S(`)
        }
        s.`)
//line gen.qtpl:41
				qw422016.N().S(f.Name)
//line gen.qtpl:41
				qw422016.N().S(` = int32(`)
//line gen.qtpl:41
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:41
				qw422016.N().S(`)
        `)
//line gen.qtpl:42
			case "int64":
//line gen.qtpl:42
				qw422016.N().S(`
        `)
//line gen.qtpl:43
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:43
				qw422016.N().S(`, err := strconv.ParseInt(rec[`)
//line gen.qtpl:43
				qw422016.N().D(f.Position)
//line gen.qtpl:43
				qw422016.N().S(`], 0, 64)
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line gen.qtpl:45
				qw422016.N().S(f.Name)
//line gen.qtpl:45
				qw422016.N().S(` at index: %d", `)
//line gen.qtpl:45
				qw422016.N().D(f.Position)
//line gen.qtpl:45
				qw422016.N().S(`)
        }
        s.`)
//line gen.qtpl:47
				qw422016.N().S(f.Name)
//line gen.qtpl:47
				qw422016.N().S(` = `)
//line gen.qtpl:47
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:47
				qw422016.N().S(`
        `)
//line gen.qtpl:48
			case "float32":
//line gen.qtpl:48
				qw422016.N().S(`
        `)
//line gen.qtpl:49
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:49
				qw422016.N().S(`, err := strconv.ParseFloat(rec[`)
//line gen.qtpl:49
				qw422016.N().D(f.Position)
//line gen.qtpl:49
				qw422016.N().S(`], 32)
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line gen.qtpl:51
				qw422016.N().S(f.Name)
//line gen.qtpl:51
				qw422016.N().S(` at index: %d", `)
//line gen.qtpl:51
				qw422016.N().D(f.Position)
//line gen.qtpl:51
				qw422016.N().S(`)
        }
        s.`)
//line gen.qtpl:53
				qw422016.N().S(f.Name)
//line gen.qtpl:53
				qw422016.N().S(` = float32(`)
//line gen.qtpl:53
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:53
				qw422016.N().S(`)
        `)
//line gen.qtpl:54
			case "float64":
//line gen.qtpl:54
				qw422016.N().S(`
        `)
//line gen.qtpl:55
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:55
				qw422016.N().S(`, err := strconv.ParseFloat(rec[`)
//line gen.qtpl:55
				qw422016.N().D(f.Position)
//line gen.qtpl:55
				qw422016.N().S(`], 64)
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line gen.qtpl:57
				qw422016.N().S(f.Name)
//line gen.qtpl:57
				qw422016.N().S(` at index: %d", `)
//line gen.qtpl:57
				qw422016.N().D(f.Position)
//line gen.qtpl:57
				qw422016.N().S(`)
        }
        s.`)
//line gen.qtpl:59
				qw422016.N().S(f.Name)
//line gen.qtpl:59
				qw422016.N().S(` = `)
//line gen.qtpl:59
				qw422016.N().S(strings.ToLower(f.Name))
//line gen.qtpl:59
				qw422016.N().S(`
        `)
//line gen.qtpl:60
			}
//line gen.qtpl:60
			qw422016.N().S(`
        `)
//line gen.qtpl:61
			if f.Omitempty {
//line gen.qtpl:61
				qw422016.N().S(`
        }
        `)
//line gen.qtpl:63
			}
//line gen.qtpl:63
			qw422016.N().S(`

    `)
//line gen.qtpl:65
		}
//line gen.qtpl:65
		qw422016.N().S(`
    return nil
}

`)
//line gen.qtpl:69
	}
//line gen.qtpl:69
	qw422016.N().S(`
`)
//line gen.qtpl:70
}

//line gen.qtpl:70
func WriteCsvTemplate(qq422016 qtio422016.Writer, ctx Context) {
//line gen.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
//line gen.qtpl:70
	StreamCsvTemplate(qw422016, ctx)
//line gen.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line gen.qtpl:70
}

//line gen.qtpl:70
func CsvTemplate(ctx Context) string {
//line gen.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
//line gen.qtpl:70
	WriteCsvTemplate(qb422016, ctx)
//line gen.qtpl:70
	qs422016 := string(qb422016.B)
//line gen.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
//line gen.qtpl:70
	return qs422016
//line gen.qtpl:70
}
